### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by drewlane** [kaia-c/py2Class#2]
I found a few typos:

line 69: chice
line 82: optaining
line 156: arithmatic
line 174: minumum
line 179: calcMad

Otherwise good, I like the use of the # as this seems consistent with the instructors style. I was thinking we might want to stick with the # instead of the """ in the future.

**Comment by karnajohnson** [comment]
I fixed those errors. I think we're good to go.

**Comment by kaia-c** [comment]
Thanks guys - I'll go ahead and turn it in.
